default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # using DATABASE_URL

test:
  <<: *default
  # using DATABASE_URL

production:
  <<: *default
  # Use the DATABASE_URL env variable
