default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ycurve_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: ycurve_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: ycurve_prod
  host:     <%= ENV['YCURVE_DBHOST'] %>
  username: <%= ENV['YCURVE_USERNAME'] %>
  password: <%= ENV['YCURVE_PASSWORD'] %>
